server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
  profiles:
     active: native
  security:
    user:
      password: 123456