version: "3"
services:
  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - mysql-service
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=auth_service_db
    ports: 
      - "3305:3306"
  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    image: account-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - mysql-service
    depends_on:
      - mysqldb
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: auth-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mysql-service
    depends_on:
      - mysqldb

networks:
  mysql-service: