spring:
  application:
    name: account-service
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_service_db
    username: root
    password: username
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: true

