spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_service_db
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        ddl-auto: true
server:
  port: 8081